apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: gitops-sandbox-mq
  owner: gitops-sandbox-mq
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/gitops-sandbox-mq/multi-tenancy-gitops-apps.git
