apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgCOi7dLFxYKZYZHdVbxIS4cEAGkmct7or4/l3Uo5cO+elq6x0BHK5J41+8OsK2RXQGfFS6C/r0k+SPPDrSij+H/N7+Uw1o2xWwmy0cfMDW44tOmrUZc/wtncvPBk+g/j/kETha7Rn1Y5bD9m0o1vuKLqKzuR/KyXT9+kXH4uR4UI6sHDlqredNh2AdBZZtZrA6GGnMK2CNyfCxcRZmwl6xVAg+Oco590C0VnqAvwVFF3t69FHXRGGdcY91h7jIfRpzk8We1Q/3Urljd8oNJvCEhhJ81Ywsd1wJqjD2m+NtdSMq7kKqB+qAs76H/ctuu+8vlEqQGRH/ZRcKVd/xa76qteWubR17smOlC3sNOdPS9OCPDaaCNhwb/0QTvJplyiSczV53OFMMABxGpOkGVblsiXkAFH40FrFKNzl9WWS+NLkQy2KwWoy8kQCJ90IvYuNliI65YzBwaXVKj33ufrvI/VzIPHe6HM2qeZsxO+BG4WP8gBHvAShGNaRxXDaJQZ5kQNXMlCvC486w2m0uoKwR3ondKc3vvrzAlqbn3rxmWMPUZW81D3NmI2GPbZRYwNvnPKM0ZBZZP6OaWEgZpouRCfg7PZGCcyMy8CyLX0z0ft7j6286PQ1pu0/8ThPDUKMOlYJFRLweIwaZF0SD9jOIVzlf3XCbPEd9qPKB4URPtuUsyK3SoH5qwcMwqyKzzh55L0vxCCg2jD8Ls4npIMlqA+yS1VXydnlTrJCfS/sMCGtNes7Am9LiJF74BQnWYdRuvCe3YnZTLVC/3UnNiT1mClHSiTN5z2P368DEVr6KGj6oQ2szeYRfPm55djFKsUYqDV/qEafMMxFhwLv+fcyhk/xIRch4NVUqbrJg+K6fKHDyg1K6uH483bjD2oqe0KwDZCr+U09JKkI7FmB/XY3ipXtW1lEiMIF3xSA3lXP6Cug==
    IBM_ENTITLED_REGISTRY_USER: AgCPXElS+0a0WAh8CJ5N1nXvtT78TEX9P+WjdK8YwW8DGIDxYpuIAW16E8yvBlRzt37mJ2vTWP3zF9N8L04pQf+jkzZK5pBmvY0j0nmEVrHPhNVDx+gzGrCAFq47EphTH5QvaI5sVsocfpiPG6aPCcC6cgV+TYaHXMufqK2ZytzqgS1AOXXNa/hgTIW0x5OPuQWLyiHmgynQQtbgvZtTYatBUsqHatHSCosnxsUReEypu+397aBef1QO99rP9uUbqRHI4dui4t94AEgfNkYGBV5CeDIdvlaf1RQ58A1N11EZsghnTaVik/PTeb1xJYyMSqwFgGx1zfy1yOBOK50ydgcHFh0ALY2WXF/cvSGU3LiihSJNaEs+t5pCzqY6B6NiyevbTzpPZFk83zH2BT+bfrk64lVhpjplrLa69AaWilc9ZvH+njyvpRc/gYJP5nQay6qMazxPAnDBUClhzYT9nAlDwMmSSuwdvKBkRbvCXxzPlH6GasfkkbGGsj8AsawAv+0PNj/OeU+R0kT0Toi/ETpaMKvWSdtGwGHdUBs28+FyLps8DBRLDH43616LSwYbUEqKlSzGYX1fXHtzJNjqFPd4uwkbZEMq+fbcuqdfAnvpbvEy8fmXjxz6Pp1Ux+XnKBhMOIK2qhoTl8UveFOrx9SMm/FwRXvEZOAOPJqyZBxNJFP6n/d7nmKrAH0ofzGqb0HrwQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

